### Get All Products
GET http://localhost:8081/products

### Get Product
GET http://localhost:8081/products/1bda0513-1e43-4076-8034-57fa99ebf2aa

### Create Product - valid use case
POST http://localhost:8081/products
Content-Type: application/json

{
    "name": "Product 1",
    "description": "Description for Product 1",
    "price": 19.99
}

### Create Product - invalid use case - name is blank
POST http://localhost:8081/products
Content-Type: application/json

{
    "name": "",
    "description": "Description for Product 1",
    "price": 19.99
}

### Create Product - invalid use case - description is too long
POST http://localhost:8081/products
Content-Type: application/json

{
    "name": "Product 1",
    "description": "Description for Product 1 is too long...........................................................................................................................",
    "price": 19.99
}

### Create Product - invalid use case - price is invalid
POST http://localhost:8081/products
Content-Type: application/json

{
    "name": "Product 1",
    "description": "Description for Product 1",
    "price": -19.99
}

### Get All Orders
GET http://localhost:8082/orders

### Create Order - valid use case
POST http://localhost:8082/orders
Content-Type: application/json

{
    "customerId": "d7e2b910-f2f4-48de-9fdf-db3ae27efb90",
    "items": [
        {
            "productId": "33b525be-a713-4afb-a111-785d603b02e4",
            "quantity": 2,
            "price": 999.99
        }
    ]
}

### Create Order - valid use case (several items)
POST http://localhost:8082/orders
Content-Type: application/json

{
    "customerId": "b3c525be-a7d3-4aeb-a411-785d603b02e4",
    "items": [
        {
            "productId": "33b525be-a713-4afb-a111-785d603b02e4",
            "quantity": 2,
            "price": 999.99
        },
        {
            "productId": "a64b7c22-7dbf-4e0c-800f-8a48d93f17c5",
            "quantity": 4,
            "price": 199.99
        }
    ]
}


### Create Order - invalid use case - price does not match product price
POST http://localhost:8082/orders
Content-Type: application/json

{
    "customerId": "d7e2b910-f2f4-48de-9fdf-db3ae27efb90",
    "items": [
        {
            "productId": "33b525be-a713-4afb-a111-785d603b02e4",
            "quantity": 2,
            "price": 19.99
        }
    ]
}

### Create Order - invalid use case - product does not exist
POST http://localhost:8082/orders
Content-Type: application/json

{
    "customerId": "d7e2b910-f2f4-48de-9fdf-db3ae27efb90",
    "items": [
        {
            "productId": "1bda0513-1e43-4076-8034-57fa99ebf2aa",
            "quantity": 2,
            "price": 19.99
        }
    ]
}

### Create Order - invalid use case - no customerId
POST http://localhost:8082/orders
Content-Type: application/json

{
    "customerId": "",
    "items": [
        {
            "productId": "1bda0513-1e43-4076-8034-57fa99ebf2aa",
            "quantity": 2,
            "price": 19.99
        }
    ]
}

### Create Order - invalid use case - customerId should be a valid UUID
POST http://localhost:8082/orders
Content-Type: application/json

{
    "customerId": "12345",
    "items": [
        {
            "productId": "1bda0513-1e43-4076-8034-57fa99ebf2aa",
            "quantity": 2,
            "price": 19.99
        }
    ]
}

### Create Order - invalid use case - no items
POST http://localhost:8082/orders
Content-Type: application/json

{
    "customerId": "d7e2b910-f2f4-48de-9fdf-db3ae27efb90",
    "items": []
}

### Create Order - invalid use case - quantity is invalid

POST http://localhost:8082/orders
Content-Type: application/json

{
    "customerId": "d7e2b910-f2f4-48de-9fdf-db3ae27efb90",
    "items": [
        {
            "productId": "1bda0513-1e43-4076-8034-57fa99ebf2aa",
            "quantity": -2,
            "price": 19.99
        }
    ]
}

### Create Order - invalid use case - price is invalid

POST http://localhost:8082/orders
Content-Type: application/json

{
    "customerId": "d7e2b910-f2f4-48de-9fdf-db3ae27efb90",
    "items": [
        {
            "productId": "1bda0513-1e43-4076-8034-57fa99ebf2aa",
            "quantity": 2,
            "price": -19.99
        }
    ]
}

### Create Order - invalid use case - product id is invalid

POST http://localhost:8082/orders
Content-Type: application/json

{
    "customerId": "d7e2b910-f2f4-48de-9fdf-db3ae27efb90",
    "items": [
        {
            "productId": "",
            "quantity": 2,
            "price": 19.99
        }
    ]
}

### Get Order Service Metrics for Prometheus
GET http://localhost:8082/actuator/prometheus   

### Get All Stock Items
GET http://localhost:8083/stocks

### Add Stock - valid use case
POST http://localhost:8083/stocks
Content-Type: application/json

{
    "productId": "33b525be-a713-4afb-a111-785d603b02e4",
    "quantity": 5
}

### Add Stock - invalid use case - quantity is negative
POST http://localhost:8083/stocks
Content-Type: application/json

{
    "productId": "33b525be-a713-4afb-a111-785d603b02e4",
    "quantity": -10
}

### Add Stock - invalid use case - product id is invalid
POST http://localhost:8083/stocks
Content-Type: application/json

{
    "productId": "foo",
    "quantity": 10
}
