### Get All Products
GET http://localhost:8081/products

### Get Product
GET http://localhost:8081/products/1bda0513-1e43-4076-8034-57fa99ebf2aa

### Create Product - valid use case
POST http://localhost:8081/products
Content-Type: application/json

{
    "name": "Product 1",
    "description": "Description for Product 1",
    "price": 19.99
}

### Create Product - invalid use case - name is blank
POST http://localhost:8081/products
Content-Type: application/json

{
    "name": "",
    "description": "Description for Product 1",
    "price": 19.99
}

### Create Product - invalid use case - description is too long
POST http://localhost:8081/products
Content-Type: application/json

{
    "name": "Product 1",
    "description": "Description for Product 1 is too long...........................................................................................................................",
    "price": 19.99
}

### Create Product - invalid use case - price is invalid
POST http://localhost:8081/products
Content-Type: application/json

{
    "name": "Product 1",
    "description": "Description for Product 1",
    "price": -19.99
}

### Create Order - valid use case
POST http://localhost:8082/orders
Content-Type: application/json

{
    "customerId": "12345",
    "items": [
        {
            "productId": "db97e9a2-1e19-4d70-bc1f-8e212e4c3b0a",
            "quantity": 2,
            "price": 19.99
        }
    ]
}

### Create Order - invalid use case - product does not exist
POST http://localhost:8082/orders
Content-Type: application/json

{
    "customerId": "12345",
    "items": [
        {
            "productId": "1bda0513-1e43-4076-8034-57fa99ebf2aa",
            "quantity": 2,
            "price": 19.99
        }
    ]
}

### Create Order - invalid use case - no customerId
POST http://localhost:8082/orders
Content-Type: application/json

{
    "customerId": "",
    "items": [
        {
            "productId": "1bda0513-1e43-4076-8034-57fa99ebf2aa",
            "quantity": 2,
            "price": 19.99
        }
    ]
}

### Create Order - invalid use case - no items
POST http://localhost:8082/orders
Content-Type: application/json

{
    "customerId": "12345",
    "items": []
}

### Create Order - invalid use case - quantity is invalid

POST http://localhost:8082/orders
Content-Type: application/json

{
    "customerId": "12345",
    "items": [
        {
            "productId": "1bda0513-1e43-4076-8034-57fa99ebf2aa",
            "quantity": -2,
            "price": 19.99
        }
    ]
}

### Create Order - invalid use case - price is invalid

POST http://localhost:8082/orders
Content-Type: application/json

{
    "customerId": "12345",
    "items": [
        {
            "productId": "1bda0513-1e43-4076-8034-57fa99ebf2aa",
            "quantity": 2,
            "price": -19.99
        }
    ]
}

### Create Order - invalid use case - product id is invalid

POST http://localhost:8082/orders
Content-Type: application/json

{
    "customerId": "12345",
    "items": [
        {
            "productId": "",
            "quantity": 2,
            "price": 19.99
        }
    ]
}