spring:
  application:
    name: stock
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:stockdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  kafka:
    bootstrap-servers: "${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: all
      retries: 3
    properties:
      schema:
        registry:
          url: "${SCHEMA_REGISTRY_URL:http://localhost:8085}"

server:
  port: 8083

app:
  product-service:
    url: "${PRODUCT_SERVICE_URL:http://localhost:8081}"

management:
  endpoints:
    web:
      exposure:
        include: health,circuitbreakers,metrics,tracing,prometheus
  health:
    circuitbreakers:
      enabled: true
  # Actuator Micrometer Tracing (Zipkin)
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: "${ZIPKIN_URL:http://localhost:9411/api/v2/spans}"

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

kafka-config:
  bootstrap-servers: "${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}"
  schema-registry-url-key: schema.registry.url
  schema-registry-url: ${SCHEMA_REGISTRY_URL:http://localhost:8085}
  
kafka-producer-config:
  key-serializer-class: org.apache.kafka.common.serialization.StringSerializer
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  compression-type: none
  acks: all
  batch-size: 1638400  
  linger-ms: 5
  request-timeout-ms: 60000
  retry-count: 5