FROM eclipse-temurin:25-jre
WORKDIR /app
# Non-root user for security
RUN groupadd -r appgroup && useradd -r -g appgroup appuser
# Copy the already built JAR from the builder step in GitHub Actions
COPY ./product-service/target/*.jar app.jar
# Ownership
RUN chown appuser:appgroup app.jar
USER appuser
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]
