spring:
  cloud:
    aws:
      region:
        static: ${AWS_REGION:eu-west-3}
      endpoint: ${AWS_ENDPOINT:}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:test}
        secret-key: ${AWS_SECRET_ACCESS_KEY:test}
      sqs:
        enabled: true
      sns:
        enabled: true
