spring:
  cloud:
    aws:
      region:
        static: eu-west-3
      credentials:
        access-key: test
        secret-key: test
      endpoint: http://localstack:4566
      sqs:
        enabled: true
      sns:
        enabled: true
