spring.application.name=order

server.port=8082

app.product-service.url=${PRODUCT_SERVICE_URL:http://localhost:8081}

# Resilience4j Circuit Breaker Configuration

# pour rendre disponible l'état des circuits breakers dans les endpoints d'actuator (actuator/circuitbreakers)
resilience4j.circuitbreaker.instances.productService.register-health-indicator=true
# sliding-window-size: nombre de dernières appels à considérer pour calculer le taux de réussite/échec
resilience4j.circuitbreaker.instances.productService.sliding-window-size=10
# minimum-number-of-calls: nombre minimum d'appels avant que le circuit breaker puisse calculer le taux de réussite/échec
resilience4j.circuitbreaker.instances.productService.minimum-number-of-calls=5
# failure-rate-threshold: pourcentage d'échecs à partir duquel le circuit breaker passe à l'état OPEN
resilience4j.circuitbreaker.instances.productService.failure-rate-threshold=50
# wait-duration-in-open-state: durée pendant laquelle le circuit breaker reste à l'état OPEN avant de passer à HALF_OPEN
resilience4j.circuitbreaker.instances.productService.wait-duration-in-open-state=10s
# permitted-number-of-calls-in-half-open-state: nombre d'appels autorisés lorsque le circuit breaker est à l'état HALF_OPEN pour tester si le service est de nouveau opérationnel  
resilience4j.circuitbreaker.instances.productService.permitted-number-of-calls-in-half-open-state=3
# automatic-transition-from-open-to-half-open-enabled: permet au circuit breaker de passer automatiquement de l'état OPEN à HALF_OPEN après la durée spécifiée
resilience4j.circuitbreaker.instances.productService.automatic-transition-from-open-to-half-open-enabled=true

# Actuator endpoints
management.endpoints.web.exposure.include=health,circuitbreakers
management.health.circuitbreakers.enabled=true