/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ecommerce.common.avro.event;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class OrderCreatedAvroEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 294619282493439626L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrderCreatedAvroEvent\",\"namespace\":\"com.ecommerce.common.avro.event\",\"fields\":[{\"name\":\"orderId\",\"type\":\"string\",\"doc\":\"Unique identifier of the order\"},{\"name\":\"customerId\",\"type\":\"string\",\"doc\":\"Unique identifier of the customer\"},{\"name\":\"orderStatus\",\"type\":\"string\",\"doc\":\"Status of the order (PENDING, CONFIRMED, etc.)\"},{\"name\":\"createdAt\",\"type\":\"long\",\"doc\":\"Timestamp when the order was created (milliseconds since epoch)\"},{\"name\":\"items\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"OrderItem\",\"fields\":[{\"name\":\"productId\",\"type\":\"string\",\"doc\":\"Product identifier\"},{\"name\":\"quantity\",\"type\":\"int\",\"doc\":\"Quantity ordered\"},{\"name\":\"price\",\"type\":\"double\",\"doc\":\"Price per unit\"}]}},\"doc\":\"List of items in the order\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OrderCreatedAvroEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OrderCreatedAvroEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<OrderCreatedAvroEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<OrderCreatedAvroEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<OrderCreatedAvroEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this OrderCreatedAvroEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a OrderCreatedAvroEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a OrderCreatedAvroEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static OrderCreatedAvroEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Unique identifier of the order */
  private java.lang.CharSequence orderId;
  /** Unique identifier of the customer */
  private java.lang.CharSequence customerId;
  /** Status of the order (PENDING, CONFIRMED, etc.) */
  private java.lang.CharSequence orderStatus;
  /** Timestamp when the order was created (milliseconds since epoch) */
  private long createdAt;
  /** List of items in the order */
  private java.util.List<com.ecommerce.common.avro.event.OrderItem> items;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OrderCreatedAvroEvent() {}

  /**
   * All-args constructor.
   * @param orderId Unique identifier of the order
   * @param customerId Unique identifier of the customer
   * @param orderStatus Status of the order (PENDING, CONFIRMED, etc.)
   * @param createdAt Timestamp when the order was created (milliseconds since epoch)
   * @param items List of items in the order
   */
  public OrderCreatedAvroEvent(java.lang.CharSequence orderId, java.lang.CharSequence customerId, java.lang.CharSequence orderStatus, java.lang.Long createdAt, java.util.List<com.ecommerce.common.avro.event.OrderItem> items) {
    this.orderId = orderId;
    this.customerId = customerId;
    this.orderStatus = orderStatus;
    this.createdAt = createdAt;
    this.items = items;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return orderId;
    case 1: return customerId;
    case 2: return orderStatus;
    case 3: return createdAt;
    case 4: return items;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: orderId = (java.lang.CharSequence)value$; break;
    case 1: customerId = (java.lang.CharSequence)value$; break;
    case 2: orderStatus = (java.lang.CharSequence)value$; break;
    case 3: createdAt = (java.lang.Long)value$; break;
    case 4: items = (java.util.List<com.ecommerce.common.avro.event.OrderItem>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return Unique identifier of the order
   */
  public java.lang.CharSequence getOrderId() {
    return orderId;
  }


  /**
   * Sets the value of the 'orderId' field.
   * Unique identifier of the order
   * @param value the value to set.
   */
  public void setOrderId(java.lang.CharSequence value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'customerId' field.
   * @return Unique identifier of the customer
   */
  public java.lang.CharSequence getCustomerId() {
    return customerId;
  }


  /**
   * Sets the value of the 'customerId' field.
   * Unique identifier of the customer
   * @param value the value to set.
   */
  public void setCustomerId(java.lang.CharSequence value) {
    this.customerId = value;
  }

  /**
   * Gets the value of the 'orderStatus' field.
   * @return Status of the order (PENDING, CONFIRMED, etc.)
   */
  public java.lang.CharSequence getOrderStatus() {
    return orderStatus;
  }


  /**
   * Sets the value of the 'orderStatus' field.
   * Status of the order (PENDING, CONFIRMED, etc.)
   * @param value the value to set.
   */
  public void setOrderStatus(java.lang.CharSequence value) {
    this.orderStatus = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return Timestamp when the order was created (milliseconds since epoch)
   */
  public long getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * Timestamp when the order was created (milliseconds since epoch)
   * @param value the value to set.
   */
  public void setCreatedAt(long value) {
    this.createdAt = value;
  }

  /**
   * Gets the value of the 'items' field.
   * @return List of items in the order
   */
  public java.util.List<com.ecommerce.common.avro.event.OrderItem> getItems() {
    return items;
  }


  /**
   * Sets the value of the 'items' field.
   * List of items in the order
   * @param value the value to set.
   */
  public void setItems(java.util.List<com.ecommerce.common.avro.event.OrderItem> value) {
    this.items = value;
  }

  /**
   * Creates a new OrderCreatedAvroEvent RecordBuilder.
   * @return A new OrderCreatedAvroEvent RecordBuilder
   */
  public static com.ecommerce.common.avro.event.OrderCreatedAvroEvent.Builder newBuilder() {
    return new com.ecommerce.common.avro.event.OrderCreatedAvroEvent.Builder();
  }

  /**
   * Creates a new OrderCreatedAvroEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OrderCreatedAvroEvent RecordBuilder
   */
  public static com.ecommerce.common.avro.event.OrderCreatedAvroEvent.Builder newBuilder(com.ecommerce.common.avro.event.OrderCreatedAvroEvent.Builder other) {
    if (other == null) {
      return new com.ecommerce.common.avro.event.OrderCreatedAvroEvent.Builder();
    } else {
      return new com.ecommerce.common.avro.event.OrderCreatedAvroEvent.Builder(other);
    }
  }

  /**
   * Creates a new OrderCreatedAvroEvent RecordBuilder by copying an existing OrderCreatedAvroEvent instance.
   * @param other The existing instance to copy.
   * @return A new OrderCreatedAvroEvent RecordBuilder
   */
  public static com.ecommerce.common.avro.event.OrderCreatedAvroEvent.Builder newBuilder(com.ecommerce.common.avro.event.OrderCreatedAvroEvent other) {
    if (other == null) {
      return new com.ecommerce.common.avro.event.OrderCreatedAvroEvent.Builder();
    } else {
      return new com.ecommerce.common.avro.event.OrderCreatedAvroEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for OrderCreatedAvroEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderCreatedAvroEvent>
    implements org.apache.avro.data.RecordBuilder<OrderCreatedAvroEvent> {

    /** Unique identifier of the order */
    private java.lang.CharSequence orderId;
    /** Unique identifier of the customer */
    private java.lang.CharSequence customerId;
    /** Status of the order (PENDING, CONFIRMED, etc.) */
    private java.lang.CharSequence orderStatus;
    /** Timestamp when the order was created (milliseconds since epoch) */
    private long createdAt;
    /** List of items in the order */
    private java.util.List<com.ecommerce.common.avro.event.OrderItem> items;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ecommerce.common.avro.event.OrderCreatedAvroEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.customerId)) {
        this.customerId = data().deepCopy(fields()[1].schema(), other.customerId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.orderStatus)) {
        this.orderStatus = data().deepCopy(fields()[2].schema(), other.orderStatus);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[3].schema(), other.createdAt);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.items)) {
        this.items = data().deepCopy(fields()[4].schema(), other.items);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing OrderCreatedAvroEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ecommerce.common.avro.event.OrderCreatedAvroEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.customerId)) {
        this.customerId = data().deepCopy(fields()[1].schema(), other.customerId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.orderStatus)) {
        this.orderStatus = data().deepCopy(fields()[2].schema(), other.orderStatus);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[3].schema(), other.createdAt);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.items)) {
        this.items = data().deepCopy(fields()[4].schema(), other.items);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'orderId' field.
      * Unique identifier of the order
      * @return The value.
      */
    public java.lang.CharSequence getOrderId() {
      return orderId;
    }


    /**
      * Sets the value of the 'orderId' field.
      * Unique identifier of the order
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.ecommerce.common.avro.event.OrderCreatedAvroEvent.Builder setOrderId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.orderId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * Unique identifier of the order
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'orderId' field.
      * Unique identifier of the order
      * @return This builder.
      */
    public com.ecommerce.common.avro.event.OrderCreatedAvroEvent.Builder clearOrderId() {
      orderId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'customerId' field.
      * Unique identifier of the customer
      * @return The value.
      */
    public java.lang.CharSequence getCustomerId() {
      return customerId;
    }


    /**
      * Sets the value of the 'customerId' field.
      * Unique identifier of the customer
      * @param value The value of 'customerId'.
      * @return This builder.
      */
    public com.ecommerce.common.avro.event.OrderCreatedAvroEvent.Builder setCustomerId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.customerId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'customerId' field has been set.
      * Unique identifier of the customer
      * @return True if the 'customerId' field has been set, false otherwise.
      */
    public boolean hasCustomerId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'customerId' field.
      * Unique identifier of the customer
      * @return This builder.
      */
    public com.ecommerce.common.avro.event.OrderCreatedAvroEvent.Builder clearCustomerId() {
      customerId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderStatus' field.
      * Status of the order (PENDING, CONFIRMED, etc.)
      * @return The value.
      */
    public java.lang.CharSequence getOrderStatus() {
      return orderStatus;
    }


    /**
      * Sets the value of the 'orderStatus' field.
      * Status of the order (PENDING, CONFIRMED, etc.)
      * @param value The value of 'orderStatus'.
      * @return This builder.
      */
    public com.ecommerce.common.avro.event.OrderCreatedAvroEvent.Builder setOrderStatus(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.orderStatus = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'orderStatus' field has been set.
      * Status of the order (PENDING, CONFIRMED, etc.)
      * @return True if the 'orderStatus' field has been set, false otherwise.
      */
    public boolean hasOrderStatus() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'orderStatus' field.
      * Status of the order (PENDING, CONFIRMED, etc.)
      * @return This builder.
      */
    public com.ecommerce.common.avro.event.OrderCreatedAvroEvent.Builder clearOrderStatus() {
      orderStatus = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * Timestamp when the order was created (milliseconds since epoch)
      * @return The value.
      */
    public long getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * Timestamp when the order was created (milliseconds since epoch)
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public com.ecommerce.common.avro.event.OrderCreatedAvroEvent.Builder setCreatedAt(long value) {
      validate(fields()[3], value);
      this.createdAt = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * Timestamp when the order was created (milliseconds since epoch)
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * Timestamp when the order was created (milliseconds since epoch)
      * @return This builder.
      */
    public com.ecommerce.common.avro.event.OrderCreatedAvroEvent.Builder clearCreatedAt() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'items' field.
      * List of items in the order
      * @return The value.
      */
    public java.util.List<com.ecommerce.common.avro.event.OrderItem> getItems() {
      return items;
    }


    /**
      * Sets the value of the 'items' field.
      * List of items in the order
      * @param value The value of 'items'.
      * @return This builder.
      */
    public com.ecommerce.common.avro.event.OrderCreatedAvroEvent.Builder setItems(java.util.List<com.ecommerce.common.avro.event.OrderItem> value) {
      validate(fields()[4], value);
      this.items = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'items' field has been set.
      * List of items in the order
      * @return True if the 'items' field has been set, false otherwise.
      */
    public boolean hasItems() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'items' field.
      * List of items in the order
      * @return This builder.
      */
    public com.ecommerce.common.avro.event.OrderCreatedAvroEvent.Builder clearItems() {
      items = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OrderCreatedAvroEvent build() {
      try {
        OrderCreatedAvroEvent record = new OrderCreatedAvroEvent();
        record.orderId = fieldSetFlags()[0] ? this.orderId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.customerId = fieldSetFlags()[1] ? this.customerId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.orderStatus = fieldSetFlags()[2] ? this.orderStatus : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.createdAt = fieldSetFlags()[3] ? this.createdAt : (java.lang.Long) defaultValue(fields()[3]);
        record.items = fieldSetFlags()[4] ? this.items : (java.util.List<com.ecommerce.common.avro.event.OrderItem>) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OrderCreatedAvroEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<OrderCreatedAvroEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OrderCreatedAvroEvent>
    READER$ = (org.apache.avro.io.DatumReader<OrderCreatedAvroEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.orderId);

    out.writeString(this.customerId);

    out.writeString(this.orderStatus);

    out.writeLong(this.createdAt);

    long size0 = this.items.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.ecommerce.common.avro.event.OrderItem e0: this.items) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.orderId = in.readString(this.orderId instanceof Utf8 ? (Utf8)this.orderId : null);

      this.customerId = in.readString(this.customerId instanceof Utf8 ? (Utf8)this.customerId : null);

      this.orderStatus = in.readString(this.orderStatus instanceof Utf8 ? (Utf8)this.orderStatus : null);

      this.createdAt = in.readLong();

      long size0 = in.readArrayStart();
      java.util.List<com.ecommerce.common.avro.event.OrderItem> a0 = this.items;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.ecommerce.common.avro.event.OrderItem>((int)size0, SCHEMA$.getField("items").schema());
        this.items = a0;
      } else a0.clear();
      SpecificData.Array<com.ecommerce.common.avro.event.OrderItem> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.ecommerce.common.avro.event.OrderItem>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.ecommerce.common.avro.event.OrderItem e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.ecommerce.common.avro.event.OrderItem();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.orderId = in.readString(this.orderId instanceof Utf8 ? (Utf8)this.orderId : null);
          break;

        case 1:
          this.customerId = in.readString(this.customerId instanceof Utf8 ? (Utf8)this.customerId : null);
          break;

        case 2:
          this.orderStatus = in.readString(this.orderStatus instanceof Utf8 ? (Utf8)this.orderStatus : null);
          break;

        case 3:
          this.createdAt = in.readLong();
          break;

        case 4:
          long size0 = in.readArrayStart();
          java.util.List<com.ecommerce.common.avro.event.OrderItem> a0 = this.items;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.ecommerce.common.avro.event.OrderItem>((int)size0, SCHEMA$.getField("items").schema());
            this.items = a0;
          } else a0.clear();
          SpecificData.Array<com.ecommerce.common.avro.event.OrderItem> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.ecommerce.common.avro.event.OrderItem>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.ecommerce.common.avro.event.OrderItem e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.ecommerce.common.avro.event.OrderItem();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










