/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ecommerce.common.avro.event;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class StockConfirmedAvroEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7044320008985618681L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"StockConfirmedAvroEvent\",\"namespace\":\"com.ecommerce.common.avro.event\",\"fields\":[{\"name\":\"orderId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Unique identifier of the order\"},{\"name\":\"createdAt\",\"type\":\"long\",\"doc\":\"Timestamp when the stock was confirmed (milliseconds since epoch)\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<StockConfirmedAvroEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<StockConfirmedAvroEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<StockConfirmedAvroEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<StockConfirmedAvroEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<StockConfirmedAvroEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this StockConfirmedAvroEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a StockConfirmedAvroEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a StockConfirmedAvroEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static StockConfirmedAvroEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Unique identifier of the order */
  private java.lang.String orderId;
  /** Timestamp when the stock was confirmed (milliseconds since epoch) */
  private long createdAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public StockConfirmedAvroEvent() {}

  /**
   * All-args constructor.
   * @param orderId Unique identifier of the order
   * @param createdAt Timestamp when the stock was confirmed (milliseconds since epoch)
   */
  public StockConfirmedAvroEvent(java.lang.String orderId, java.lang.Long createdAt) {
    this.orderId = orderId;
    this.createdAt = createdAt;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return orderId;
    case 1: return createdAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: orderId = value$ != null ? value$.toString() : null; break;
    case 1: createdAt = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return Unique identifier of the order
   */
  public java.lang.String getOrderId() {
    return orderId;
  }


  /**
   * Sets the value of the 'orderId' field.
   * Unique identifier of the order
   * @param value the value to set.
   */
  public void setOrderId(java.lang.String value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return Timestamp when the stock was confirmed (milliseconds since epoch)
   */
  public long getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * Timestamp when the stock was confirmed (milliseconds since epoch)
   * @param value the value to set.
   */
  public void setCreatedAt(long value) {
    this.createdAt = value;
  }

  /**
   * Creates a new StockConfirmedAvroEvent RecordBuilder.
   * @return A new StockConfirmedAvroEvent RecordBuilder
   */
  public static com.ecommerce.common.avro.event.StockConfirmedAvroEvent.Builder newBuilder() {
    return new com.ecommerce.common.avro.event.StockConfirmedAvroEvent.Builder();
  }

  /**
   * Creates a new StockConfirmedAvroEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new StockConfirmedAvroEvent RecordBuilder
   */
  public static com.ecommerce.common.avro.event.StockConfirmedAvroEvent.Builder newBuilder(com.ecommerce.common.avro.event.StockConfirmedAvroEvent.Builder other) {
    if (other == null) {
      return new com.ecommerce.common.avro.event.StockConfirmedAvroEvent.Builder();
    } else {
      return new com.ecommerce.common.avro.event.StockConfirmedAvroEvent.Builder(other);
    }
  }

  /**
   * Creates a new StockConfirmedAvroEvent RecordBuilder by copying an existing StockConfirmedAvroEvent instance.
   * @param other The existing instance to copy.
   * @return A new StockConfirmedAvroEvent RecordBuilder
   */
  public static com.ecommerce.common.avro.event.StockConfirmedAvroEvent.Builder newBuilder(com.ecommerce.common.avro.event.StockConfirmedAvroEvent other) {
    if (other == null) {
      return new com.ecommerce.common.avro.event.StockConfirmedAvroEvent.Builder();
    } else {
      return new com.ecommerce.common.avro.event.StockConfirmedAvroEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for StockConfirmedAvroEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<StockConfirmedAvroEvent>
    implements org.apache.avro.data.RecordBuilder<StockConfirmedAvroEvent> {

    /** Unique identifier of the order */
    private java.lang.String orderId;
    /** Timestamp when the stock was confirmed (milliseconds since epoch) */
    private long createdAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ecommerce.common.avro.event.StockConfirmedAvroEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[1].schema(), other.createdAt);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing StockConfirmedAvroEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ecommerce.common.avro.event.StockConfirmedAvroEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[1].schema(), other.createdAt);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'orderId' field.
      * Unique identifier of the order
      * @return The value.
      */
    public java.lang.String getOrderId() {
      return orderId;
    }


    /**
      * Sets the value of the 'orderId' field.
      * Unique identifier of the order
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.ecommerce.common.avro.event.StockConfirmedAvroEvent.Builder setOrderId(java.lang.String value) {
      validate(fields()[0], value);
      this.orderId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * Unique identifier of the order
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'orderId' field.
      * Unique identifier of the order
      * @return This builder.
      */
    public com.ecommerce.common.avro.event.StockConfirmedAvroEvent.Builder clearOrderId() {
      orderId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * Timestamp when the stock was confirmed (milliseconds since epoch)
      * @return The value.
      */
    public long getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * Timestamp when the stock was confirmed (milliseconds since epoch)
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public com.ecommerce.common.avro.event.StockConfirmedAvroEvent.Builder setCreatedAt(long value) {
      validate(fields()[1], value);
      this.createdAt = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * Timestamp when the stock was confirmed (milliseconds since epoch)
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * Timestamp when the stock was confirmed (milliseconds since epoch)
      * @return This builder.
      */
    public com.ecommerce.common.avro.event.StockConfirmedAvroEvent.Builder clearCreatedAt() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public StockConfirmedAvroEvent build() {
      try {
        StockConfirmedAvroEvent record = new StockConfirmedAvroEvent();
        record.orderId = fieldSetFlags()[0] ? this.orderId : (java.lang.String) defaultValue(fields()[0]);
        record.createdAt = fieldSetFlags()[1] ? this.createdAt : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<StockConfirmedAvroEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<StockConfirmedAvroEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<StockConfirmedAvroEvent>
    READER$ = (org.apache.avro.io.DatumReader<StockConfirmedAvroEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.orderId);

    out.writeLong(this.createdAt);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.orderId = in.readString();

      this.createdAt = in.readLong();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.orderId = in.readString();
          break;

        case 1:
          this.createdAt = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










