/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ecommerce.common.avro.event;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class StockReservedAvroEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1929333445902959440L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"StockReservedAvroEvent\",\"namespace\":\"com.ecommerce.common.avro.event\",\"fields\":[{\"name\":\"orderId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Unique identifier of the order\"},{\"name\":\"createdAt\",\"type\":\"long\",\"doc\":\"Timestamp when the stock was reserved (milliseconds since epoch)\"},{\"name\":\"items\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"StockItem\",\"fields\":[{\"name\":\"productId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Product identifier\"},{\"name\":\"quantity\",\"type\":\"int\",\"doc\":\"Quantity reserved\"}]}},\"doc\":\"List of products that were reserved\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<StockReservedAvroEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<StockReservedAvroEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<StockReservedAvroEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<StockReservedAvroEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<StockReservedAvroEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this StockReservedAvroEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a StockReservedAvroEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a StockReservedAvroEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static StockReservedAvroEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Unique identifier of the order */
  private java.lang.String orderId;
  /** Timestamp when the stock was reserved (milliseconds since epoch) */
  private long createdAt;
  /** List of products that were reserved */
  private java.util.List<com.ecommerce.common.avro.event.StockItem> items;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public StockReservedAvroEvent() {}

  /**
   * All-args constructor.
   * @param orderId Unique identifier of the order
   * @param createdAt Timestamp when the stock was reserved (milliseconds since epoch)
   * @param items List of products that were reserved
   */
  public StockReservedAvroEvent(java.lang.String orderId, java.lang.Long createdAt, java.util.List<com.ecommerce.common.avro.event.StockItem> items) {
    this.orderId = orderId;
    this.createdAt = createdAt;
    this.items = items;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return orderId;
    case 1: return createdAt;
    case 2: return items;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: orderId = value$ != null ? value$.toString() : null; break;
    case 1: createdAt = (java.lang.Long)value$; break;
    case 2: items = (java.util.List<com.ecommerce.common.avro.event.StockItem>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return Unique identifier of the order
   */
  public java.lang.String getOrderId() {
    return orderId;
  }


  /**
   * Sets the value of the 'orderId' field.
   * Unique identifier of the order
   * @param value the value to set.
   */
  public void setOrderId(java.lang.String value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return Timestamp when the stock was reserved (milliseconds since epoch)
   */
  public long getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * Timestamp when the stock was reserved (milliseconds since epoch)
   * @param value the value to set.
   */
  public void setCreatedAt(long value) {
    this.createdAt = value;
  }

  /**
   * Gets the value of the 'items' field.
   * @return List of products that were reserved
   */
  public java.util.List<com.ecommerce.common.avro.event.StockItem> getItems() {
    return items;
  }


  /**
   * Sets the value of the 'items' field.
   * List of products that were reserved
   * @param value the value to set.
   */
  public void setItems(java.util.List<com.ecommerce.common.avro.event.StockItem> value) {
    this.items = value;
  }

  /**
   * Creates a new StockReservedAvroEvent RecordBuilder.
   * @return A new StockReservedAvroEvent RecordBuilder
   */
  public static com.ecommerce.common.avro.event.StockReservedAvroEvent.Builder newBuilder() {
    return new com.ecommerce.common.avro.event.StockReservedAvroEvent.Builder();
  }

  /**
   * Creates a new StockReservedAvroEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new StockReservedAvroEvent RecordBuilder
   */
  public static com.ecommerce.common.avro.event.StockReservedAvroEvent.Builder newBuilder(com.ecommerce.common.avro.event.StockReservedAvroEvent.Builder other) {
    if (other == null) {
      return new com.ecommerce.common.avro.event.StockReservedAvroEvent.Builder();
    } else {
      return new com.ecommerce.common.avro.event.StockReservedAvroEvent.Builder(other);
    }
  }

  /**
   * Creates a new StockReservedAvroEvent RecordBuilder by copying an existing StockReservedAvroEvent instance.
   * @param other The existing instance to copy.
   * @return A new StockReservedAvroEvent RecordBuilder
   */
  public static com.ecommerce.common.avro.event.StockReservedAvroEvent.Builder newBuilder(com.ecommerce.common.avro.event.StockReservedAvroEvent other) {
    if (other == null) {
      return new com.ecommerce.common.avro.event.StockReservedAvroEvent.Builder();
    } else {
      return new com.ecommerce.common.avro.event.StockReservedAvroEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for StockReservedAvroEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<StockReservedAvroEvent>
    implements org.apache.avro.data.RecordBuilder<StockReservedAvroEvent> {

    /** Unique identifier of the order */
    private java.lang.String orderId;
    /** Timestamp when the stock was reserved (milliseconds since epoch) */
    private long createdAt;
    /** List of products that were reserved */
    private java.util.List<com.ecommerce.common.avro.event.StockItem> items;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ecommerce.common.avro.event.StockReservedAvroEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[1].schema(), other.createdAt);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.items)) {
        this.items = data().deepCopy(fields()[2].schema(), other.items);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing StockReservedAvroEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ecommerce.common.avro.event.StockReservedAvroEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[1].schema(), other.createdAt);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.items)) {
        this.items = data().deepCopy(fields()[2].schema(), other.items);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'orderId' field.
      * Unique identifier of the order
      * @return The value.
      */
    public java.lang.String getOrderId() {
      return orderId;
    }


    /**
      * Sets the value of the 'orderId' field.
      * Unique identifier of the order
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.ecommerce.common.avro.event.StockReservedAvroEvent.Builder setOrderId(java.lang.String value) {
      validate(fields()[0], value);
      this.orderId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * Unique identifier of the order
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'orderId' field.
      * Unique identifier of the order
      * @return This builder.
      */
    public com.ecommerce.common.avro.event.StockReservedAvroEvent.Builder clearOrderId() {
      orderId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * Timestamp when the stock was reserved (milliseconds since epoch)
      * @return The value.
      */
    public long getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * Timestamp when the stock was reserved (milliseconds since epoch)
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public com.ecommerce.common.avro.event.StockReservedAvroEvent.Builder setCreatedAt(long value) {
      validate(fields()[1], value);
      this.createdAt = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * Timestamp when the stock was reserved (milliseconds since epoch)
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * Timestamp when the stock was reserved (milliseconds since epoch)
      * @return This builder.
      */
    public com.ecommerce.common.avro.event.StockReservedAvroEvent.Builder clearCreatedAt() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'items' field.
      * List of products that were reserved
      * @return The value.
      */
    public java.util.List<com.ecommerce.common.avro.event.StockItem> getItems() {
      return items;
    }


    /**
      * Sets the value of the 'items' field.
      * List of products that were reserved
      * @param value The value of 'items'.
      * @return This builder.
      */
    public com.ecommerce.common.avro.event.StockReservedAvroEvent.Builder setItems(java.util.List<com.ecommerce.common.avro.event.StockItem> value) {
      validate(fields()[2], value);
      this.items = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'items' field has been set.
      * List of products that were reserved
      * @return True if the 'items' field has been set, false otherwise.
      */
    public boolean hasItems() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'items' field.
      * List of products that were reserved
      * @return This builder.
      */
    public com.ecommerce.common.avro.event.StockReservedAvroEvent.Builder clearItems() {
      items = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public StockReservedAvroEvent build() {
      try {
        StockReservedAvroEvent record = new StockReservedAvroEvent();
        record.orderId = fieldSetFlags()[0] ? this.orderId : (java.lang.String) defaultValue(fields()[0]);
        record.createdAt = fieldSetFlags()[1] ? this.createdAt : (java.lang.Long) defaultValue(fields()[1]);
        record.items = fieldSetFlags()[2] ? this.items : (java.util.List<com.ecommerce.common.avro.event.StockItem>) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<StockReservedAvroEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<StockReservedAvroEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<StockReservedAvroEvent>
    READER$ = (org.apache.avro.io.DatumReader<StockReservedAvroEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.orderId);

    out.writeLong(this.createdAt);

    long size0 = this.items.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.ecommerce.common.avro.event.StockItem e0: this.items) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.orderId = in.readString();

      this.createdAt = in.readLong();

      long size0 = in.readArrayStart();
      java.util.List<com.ecommerce.common.avro.event.StockItem> a0 = this.items;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.ecommerce.common.avro.event.StockItem>((int)size0, SCHEMA$.getField("items").schema());
        this.items = a0;
      } else a0.clear();
      SpecificData.Array<com.ecommerce.common.avro.event.StockItem> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.ecommerce.common.avro.event.StockItem>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.ecommerce.common.avro.event.StockItem e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.ecommerce.common.avro.event.StockItem();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.orderId = in.readString();
          break;

        case 1:
          this.createdAt = in.readLong();
          break;

        case 2:
          long size0 = in.readArrayStart();
          java.util.List<com.ecommerce.common.avro.event.StockItem> a0 = this.items;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.ecommerce.common.avro.event.StockItem>((int)size0, SCHEMA$.getField("items").schema());
            this.items = a0;
          } else a0.clear();
          SpecificData.Array<com.ecommerce.common.avro.event.StockItem> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.ecommerce.common.avro.event.StockItem>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.ecommerce.common.avro.event.StockItem e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.ecommerce.common.avro.event.StockItem();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










